data:
  input_pth: None
  output_pth: data/tmp/demo_output.txt

time_steps: 100


# 主交互窗口
window:
  name: demo
  size: #左上，右下脚点坐标
    - 100
    - 100 
    - 1800
    - 1200

# label设置（如校徽）
label:
  pic1:
    path: data/pic/sjtu.png
    size:
      - 80
      - 80
    pos:
      - 10
      - 10
  pic2:
    path: data/pic/nwpu.png
    size:
      - 80
      - 80
    pos:
      - 100
      - 10

# 滑动条设置
slider:
  range:
    - 0
    - 0

# 绘图窗口
figure:
  - name: temp

# 模型配置
model: 
  - out_dir: data/output
  



